# fly.toml app configuration file generated for farb-next-js on 2024-10-18T17:51:54-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'farb-next-js'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  grace_period = '3600s'  # Keep the machine running for 1 hour after last request

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
